
import java.applet.AudioClip;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author evely
 */
public class game1 extends javax.swing.JFrame {

    /**
     * Creates new form game1
     */
 
    int suma=0;
    int boton=0,suma1=0, suma2=0, suma3=0, par=0;
    public game1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("NUMBER RACE");
        setIconImage(new ImageIcon(getClass().getResource("/images/car1281px.png")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/images/car.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        
        btnConfig.setEnabled(false);
        btnPlay.setEnabled(false);
        btnTry.setEnabled(false);
        btnAbout.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTurn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAdvanced = new javax.swing.JLabel();
        lblMissing = new javax.swing.JLabel();
        lblReturns = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCounter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblWin = new javax.swing.JLabel();
        btnAbout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox<>();
        cmbPlayers = new javax.swing.JComboBox<>();
        btnStar = new javax.swing.JButton();
        lblConfig = new javax.swing.JLabel();
        btnTry = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102,90));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Dices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        lblD1.setBackground(new java.awt.Color(0, 0, 102));
        lblD1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblD1.setForeground(new java.awt.Color(0, 51, 51));
        lblD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        lblD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblD1.setOpaque(true);

        lblD2.setBackground(new java.awt.Color(0, 0, 102));
        lblD2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblD2.setForeground(new java.awt.Color(0, 51, 51));
        lblD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        lblD2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblD2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblD1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblD2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblD2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(lblD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Turn player");

        jPanel3.setBackground(new java.awt.Color(0, 0, 102,100));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Scores Zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Turn Player");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Advanced positions");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Missing positions");

        lblTurn.setBackground(new java.awt.Color(0, 0, 102));
        lblTurn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        lblTurn.setForeground(new java.awt.Color(255, 255, 255));
        lblTurn.setText("#");
        lblTurn.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Returns");

        lblAdvanced.setBackground(new java.awt.Color(0, 0, 102));
        lblAdvanced.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        lblAdvanced.setForeground(new java.awt.Color(255, 255, 255));
        lblAdvanced.setText("#");
        lblAdvanced.setOpaque(true);

        lblMissing.setBackground(new java.awt.Color(0, 0, 102));
        lblMissing.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        lblMissing.setForeground(new java.awt.Color(255, 255, 255));
        lblMissing.setText("#");
        lblMissing.setOpaque(true);

        lblReturns.setBackground(new java.awt.Color(0, 0, 102));
        lblReturns.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        lblReturns.setForeground(new java.awt.Color(255, 255, 255));
        lblReturns.setText("#");
        lblReturns.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTurn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblAdvanced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMissing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReturns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTurn))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblAdvanced))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMissing, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReturns)
                    .addComponent(jLabel10))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Pairs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCounter.setBackground(new java.awt.Color(255, 255, 255));
        lblCounter.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblCounter.setForeground(new java.awt.Color(255, 255, 255));
        lblCounter.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(0, 0, 102,100));
        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   Number Race");
        jLabel3.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car1281px.png"))); // NOI18N

        btnPlay.setBackground(new java.awt.Color(0, 0, 102));
        btnPlay.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play - Player   #");
        btnPlay.setEnabled(false);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Winner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        lblWin.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblWin.setForeground(new java.awt.Color(255, 255, 255));
        lblWin.setText("?  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lblWin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblWin)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnAbout.setBackground(new java.awt.Color(0, 0, 102));
        btnAbout.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("About Of");
        btnAbout.setEnabled(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 153,100));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Config Zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of players");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Level");

        lblLevel.setBackground(new java.awt.Color(0, 0, 102));
        lblLevel.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel.setText("-");
        lblLevel.setOpaque(true);

        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "50", "100", "200" }));

        cmbPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3" }));
        cmbPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlayersActionPerformed(evt);
            }
        });

        btnStar.setBackground(new java.awt.Color(204, 0, 0));
        btnStar.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnStar.setForeground(new java.awt.Color(255, 255, 255));
        btnStar.setText("Star Game");
        btnStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbPlayers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLevel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStar)
                .addGap(21, 21, 21))
        );

        lblConfig.setBackground(new java.awt.Color(255, 0, 0,100));
        lblConfig.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        lblConfig.setForeground(new java.awt.Color(255, 255, 255));
        lblConfig.setText("    -");
        lblConfig.setOpaque(true);

        btnTry.setBackground(new java.awt.Color(204, 0, 0));
        btnTry.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnTry.setForeground(new java.awt.Color(255, 255, 255));
        btnTry.setText("try again");
        btnTry.setEnabled(false);
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        btnConfig.setBackground(new java.awt.Color(204, 0, 0));
        btnConfig.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        btnConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnConfig.setText("config params");
        btnConfig.setEnabled(false);
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Sound");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(82, 82, 82))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTry, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbout)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfig)
                                .addGap(3, 3, 3)
                                .addComponent(lblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        /*AudioClip sonido;
        sonido=java.applet.Applet.newAudioClip(getClass().getResource("gamer/dicess.wav"));
        sonido.play();*/
        
        Random D = new Random(); //NUMEROS ALEATORIOS
        int dado1 = 0, dado2 = 0;

        dado1 = (int)(D.nextDouble()* 6 + 1);//RANGO
        dado2 = (int)(D.nextDouble()* 6 + 1);
        
               
        switch(dado1){
            case 1:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
                break;
            
            case 2:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
                break;
            
            case 3:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
                break;
            
            case 4:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
                break;
            
            case 5:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
                break;
            
            case 6:
                lblD1.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
                break;
            
            default:
            break;
        }

        switch(dado2){
            case 1:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/1.png")));
                break;
            
            case 2:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/2.png")));
                break;
            
            case 3:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/3.png")));
                break;
            
            case 4:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/4.png")));
                break;
            
            case 5:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/5.png")));
                break;
            
            case 6:
                lblD2.setIcon(new ImageIcon(getClass().getResource("images/6.png")));
                break;
            
            default:
            break;
        }
        
        int resta1=0,resta2=0,resta3=0, ret=0;
               
        String lev=cmbLevel.getSelectedItem().toString();//INVOCAR LOS DATOS DE NIVEL
        int level=Integer.parseInt(lev);//CONVIERTE A int
               
        String play=cmbPlayers.getSelectedItem().toString();//INVOCAR LOS PLAYERS
        int players=Integer.parseInt(play);//CONVERTIR A INT
        
        suma=dado1+dado2;
        
        switch (players){
             
            case 1:
            {
                //JUGADOR UNO
                break;      
            }
            case 2:
            {   
                boton=boton+1;
                if(boton==3){
                    boton=1;
                }
               
                //JUGADOR UNO
                if(boton==1){
                    //SCORES ZONE
                    btnPlay.setText("Play - Player   1");//JUGADOR
                    lblTurn.setText("1");//TURNO
                    lblCounter.setText(""+suma);//SUMA DE DADOS

                    suma1=suma1+suma;
                    lblAdvanced.setText(""+suma1);//ACUMULACION

                    resta1=level-suma1;
                    lblMissing.setText(""+resta1);//MISSING 
                    lblReturns.setText("0");
                    System.out.println("Has presionado el boton  "+boton+" .");//VALIDACION INTERNA
                    
                    System.out.println("jugador 1::"+suma1);//VALIDACIO INTERNA
                    
                    //CHOQUE DE CARROS
                    if(suma1==suma2){
                        suma2=0;//DEVULEVE LO QUE AVANZO JUGADOR 2
                        lblAdvanced.setText(""+suma2);//MUESTRA EL AVANCE A CERO
                        ret=suma1-suma2;
                        lblReturns.setText(""+ret);//MUESTRA EL RETURNS
                    }
                    
                    //PARES
                    if(dado1==dado2){
                        par=par+1;
                        lblWin.setText(""+par);//MUESTRA PARES
                        
                        suma1=suma1+21;//UN PAR 21 AVANCES
                        /*if(suma1<=level){
                            //lblVeint.setText("player 1 advances 21 positions");
                        }else{
                                                        
                            //lblVeint.setText("position limit exceeded");
                        }*/
                        
                        if (par>2){
                            JOptionPane.showMessageDialog(null,"::: YOU WIN ::: "
                            +"\n PLAYER ONE");//JOptionPane , APAREZCA UN CUADO DE DIALOGO
                        }
                        
                    }else{
                        
                        lblWin.setText("0");
                    }
                    
                    if(suma1>=level){
                        JOptionPane.showMessageDialog(null,"::: YOU WIN ::: "
                        +"\n PLAYER ONE");//JOptionPane , APAREZCA UN CUADO DE DIALOGO
                    }   
                }
                
                //JUGADOR DOS
                if(boton==2){
                    
                    btnPlay.setText("Play - Player   2");
                    lblTurn.setText("2");
                    lblCounter.setText(""+suma);

                    suma2=suma2+suma;
                    lblAdvanced.setText(""+suma2);

                    resta1=level-suma2;
                    lblMissing.setText(""+resta1);
                    lblReturns.setText("0");
                    System.out.println("Has presionado el boton  "+boton+" .");
                    
                    System.out.println("jugador 2::"+suma2);
                    if(suma2==0){
                        
                    }
                    if(suma2==suma1){
                        suma1=0;//DEVULEVE LO QUE AVANZO
                        lblAdvanced.setText(""+suma1);
                        ret=suma2-suma1;
                        lblReturns.setText(""+ret);
                    }
                    
                    if(dado1==dado2){
                        par=par+1;
                        lblWin.setText(""+par);
                        
                        suma2=suma2+21;
                        if(suma2<=level){
                            //lblVeint.setText("player 2 advances 21 positions");
                        }else{
                                                        
                            //lblVeint.setText("position limit exceeded");
                        }
                        
                        if (par>2){
                            JOptionPane.showMessageDialog(null,"::: YOU WIN ::: "
                            +"\n PLAYER TWO");//JOptionPane , APAREZCA UN CUADO DE DIALOGO
                        }
                    }else{
                        
                        lblWin.setText("0");
                    }
                    
                    if(suma2>=level){
                        JOptionPane.showMessageDialog(null,"::: YOU WIN ::: "
                        +"\n PLAYER TWO");//JOptionPane , APAREZCA UN CUADO DE DIALOGO
                    }   
                }
            }
            break;    
        
        case 3:
            {
                //JUGADOR UNO
                break;      
            }  
        default:
        break;
        }
        
        
        
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
        // TODO add your handling code here:
        lblD1.setIcon(new ImageIcon(getClass().getResource("images/question.png")));
        lblD2.setIcon(new ImageIcon(getClass().getResource("images/question.png")));

        lblCounter.setText("0");
        lblTurn.setText("0");
        lblAdvanced.setText("0");
        lblMissing.setText("0");
        lblWin.setText("0");
        
        suma1=0;
        suma2=0;
        suma3=0;
        par=0;
        
    }//GEN-LAST:event_btnTryActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        String cadena;
        cadena =JOptionPane.showInputDialog("Type Number");//CUADRO OUTPUT NUM PLAYER
      
        cmbPlayers.addItem(""+cadena);//AÑADIR JUGADORES A ITEM
        lblConfig.setText("It was added correctly");//MUESTRA EN A INTERFAZ lbl  
       
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStarActionPerformed
        // TODO add your handling code here:
        
        btnConfig.setEnabled(true);
        btnPlay.setEnabled(true);
        btnTry.setEnabled(true);
        btnAbout.setEnabled(true);
        
       
    }//GEN-LAST:event_btnStarActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Welcome to Number Race\n" +
        "free multiplayer racing game, a game developed in java" +

        "\nthat can be played with 2 or 4 players\n" +
        "\n" +"Characteristics:\n" +
        "# Play with your friends\n" +
        "# Play with 2 or more players\n" +
        "# Competition game\n" +
        "# It is free to play\n" +
        "# Best multiplayer racing game\n" +
        "# Designed for tablets and mobiles\n" +
        "\n" +"You want to play Number Raice, download now\n" +
        "Play the best racing game with friends"+

        "\n\n Developed by Evelyn Rodrìguez"+
        "\n\n and by Juan Àngel Gualguan");   
    }//GEN-LAST:event_btnAboutActionPerformed

    private void cmbPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlayersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AudioClip sonido1;
        sonido1=java.applet.Applet.newAudioClip(getClass().getResource("gamer/audio1.wav"));
        sonido1.play();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run(){
                new game1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStar;
    private javax.swing.JButton btnTry;
    private javax.swing.JComboBox<String> cmbLevel;
    private javax.swing.JComboBox<String> cmbPlayers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAdvanced;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMissing;
    private javax.swing.JLabel lblReturns;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblWin;
    // End of variables declaration//GEN-END:variables

   
}
